import { expect, test } from 'bun:test'

const ui = await import('../dist/ui/index.js')
const components = await import('../dist/components/index.js')
const blocks = await import('../dist/blocks/index.js')
const utils = await import('../dist/utils/index.js')

test('loads the four documented public modules', () => {
  expect(ui.Button).toBeDefined()
  expect(ui.buttonSizes).toEqual(['sm', 'md', 'lg'])
  expect(ui.Field).toBeDefined()
  expect(ui.Form).toBeDefined()
  expect(ui.Group).toBeDefined()
  expect(ui.Input).toBeDefined()
  expect(ui.inputSizes).toEqual(['sm', 'md', 'lg'])
  expect(ui.InputGroup).toBeDefined()
  expect(ui.Kbd).toBeDefined()
  expect(ui.Separator).toBeDefined()
  expect(ui.Text).toBeDefined()
  expect(ui.textSizes).toEqual(['sm', 'md', 'lg'])
  expect(components.SelectProperty).toBeDefined()
  expect(components.Editable).toBeDefined()
  expect(blocks.Kanban).toBeDefined()
  expect(blocks.DataGrid).toBeDefined()
  expect(blocks.DetailSheet).toBeDefined()
  expect(blocks.FilterBuilder).toBeDefined()
  expect(utils.cn('tc96')).toBe('tc96')
})
